buildpacks = [
  { id = "io.projectriff.java",                uri = "https://storage.googleapis.com/projectriff/java-function-buildpack/io.projectriff.java-0.1.4.tgz" },
  { id = "io.projectriff.node",                uri = "https://storage.googleapis.com/projectriff/node-function-buildpack/io.projectriff.node-0.1.0.tgz" },
  { id = "io.projectriff.command",             uri = "https://storage.googleapis.com/projectriff/command-function-buildpack/io.projectriff.command-0.0.8.tgz" },
  { id = "org.cloudfoundry.openjdk",           uri = "https://repo.spring.io/libs-milestone-local/org/cloudfoundry/openjdk/org.cloudfoundry.openjdk/1.0.0-M5/org.cloudfoundry.openjdk-1.0.0-M5.tgz" },
  { id = "org.cloudfoundry.buildsystem",       uri = "https://repo.spring.io/libs-milestone-local/org/cloudfoundry/buildsystem/org.cloudfoundry.buildsystem/1.0.0-M5/org.cloudfoundry.buildsystem-1.0.0-M5.tgz" },
  { id = "org.cloudfoundry.buildpacks.nodejs", uri = "https://github.com/cloudfoundry/nodejs-cnb/releases/download/v0.0.4/nodejs-cnb-0.0.4.tgz" },
  { id = "org.cloudfoundry.buildpacks.npm",    uri = "https://github.com/cloudfoundry/npm-cnb/releases/download/v0.0.4/npm-cnb-0.0.4.tgz" },
]

[[groups]]
  # java functions
  buildpacks = [
    { id = "org.cloudfoundry.openjdk",     version = "1.0.0-M5", optional = true },
    { id = "org.cloudfoundry.buildsystem", version = "1.0.0-M5", optional = true },
    { id = "io.projectriff.java", version = "0.1.4" },
  ]

[[groups]]
  # node functions
  buildpacks = [
    { id = "org.cloudfoundry.buildpacks.nodejs", version = "0.0.4", optional = true },
    { id = "org.cloudfoundry.buildpacks.npm",    version = "0.0.4", optional = true },
    { id = "io.projectriff.node", version = "0.1.0" },
  ]
  
[[groups]]
  # command functions
  buildpacks = [
    { id = "io.projectriff.command", version = "0.0.8" },
  ]

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "packs/build:0.1.0"
  run-image = "packs/run:0.1.0"
