[common]
repo = "https://github.com/projectriff/fats"
refspec = "c346e1687dc635602552dd864e133feb1dea547f"
input = "builder"
content-type = "text/plain"
output = "BUILDER"

[[testcases]]
sub-path = "functions/uppercase/java"

[[testcases]]
sub-path = "functions/uppercase/java-boot"

[[testcases]]
sub-path = "functions/uppercase/node"

[[testcases]]
sub-path = "functions/uppercase/npm"
skip-rebuild = true

[[testcases]]
sub-path = "functions/uppercase/command"
